"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
require("./globals.css");
var google_1 = require("next/font/google");
var utils_1 = require("@/shared/ui/utils");
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
var fontSans = (0, google_1.Inter)({
    subsets: ["latin"],
    variable: "--font-sans",
});
function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <body className={(0, utils_1.cn)("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        {children}
      </body>
    </html>);
}
exports.default = RootLayout;
